<project name="pdb_project" version="1.1">
    <ProjectDirectory>
        C:\Actelprj\a2f-actel-dev-brd-F\pdb_project
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LogFile>
        C:\Actelprj\a2f-actel-dev-brd-F\pdb_project\pdb_project.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <programmer status="enable" type="FlashPro3" revision="UndefRev" connection="usb2.0">
        <name>
            51857
        </name>
        <id>
            51857
        </id>
    </programmer>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
        </Hardware>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                4000000
            </MaxTCK>
        </Algo>
    </configuration>
</project>
